services:
  - type: web
    name: toursafe-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: AI_SERVICE_URL
        value: https://toursafe-ai.onrender.com

  - type: web
    name: toursafe-ai
    env: python
    plan: free
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
